apiVersion: apps/v1
kind: Deployment
metadata:
  name: codeguardian-deployment
  labels:
    app: codeguardian
spec:
  selector:
    matchLabels:
      app: codeguardian
  template:
    metadata:
      labels:
        app: codeguardian
    spec:
      containers:
      - name: git-sync
        image: k8s.gcr.io/git-sync:v3.1.3
        volumeMounts:
        - name: www-data
          mountPath: /data
        env:
        - name: GIT_SYNC_REPO
          value: "https://github.com/abhijithb200/PHP-demo.git" ##repo-path-you-want-to-clone
        - name: GIT_SYNC_BRANCH
          value: "main" ##repo-branch
        - name: GIT_SYNC_ROOT
          value: /data
        - name: GIT_SYNC_DEST
          value: "" ##path-where-you-want-to-clone
        - name: GIT_SYNC_PERIOD
          value: "20"
        - name: GIT_SYNC_ONE_TIME
          value: "false"
        securityContext:
          runAsUser: 0
      - name: php
        image: php:7.2-apache
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: "/var/www/html/"
          name: www-data
      volumes:
      - name: www-data
        emptyDir: {}
