apiVersion: apps/v1
kind: Deployment
metadata:
  name: codeguardianxss-testdeployment
  labels:
    app: codeguardian
spec:
  selector:
    matchLabels:
      app: codeguardian
  template:
    metadata:
      labels:
        app: codeguardian
    spec:
      containers:
      - name: php-test
        image: php:7.2-apache
        env:
        - name: GITHASH
          value: "thisisafakegithash"

