apiVersion: v1
kind: Secret
metadata:
    name: mongodb-secret    # name of the secret
type: Opaque                # default cred type
data:
    mongo-root-username: dXNlcm5hbWU=   # value encoded in base64
    mongo-root-password: cGFzc3dvcmQ=